#!/bin/bash

# K-Jarvis Open Source Setup Script
# Generates secure secrets and initializes configuration for quick start.

echo "🚀 Initializing K-Jarvis Open Source Environment..."

# Function to generate random hex string
generate_secret() {
    openssl rand -hex 32
}

# Function to generate random url-safe string (simulating client id)
generate_id() {
    openssl rand -hex 16
}

# Check if .env exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists. Backing up to .env.bak..."
    cp .env .env.bak
fi

echo "🔑 Generating secure keys..."

# Generate Secrets
JWT_SECRET="fixed_jwt_secret_for_stable_testing_12345"
ADMIN_PASSWORD="admin123!@#" # Fixed password for consistent testing
KJARVIS_CLIENT_ID="kjarvis_fixed_client_id"
KJARVIS_CLIENT_SECRET="kjarvis_fixed_client_secret_secure_value"
KARC_CLIENT_ID="karc_fixed_client_id"
KARC_CLIENT_SECRET="karc_fixed_client_secret_secure_value"

echo "📝 Creating .env file..."

cat > .env <<EOL
# ==============================================
# K-Jarvis Open Source Configuration
# Auto-generated by init-kjarvis.sh on $(date)
# ==============================================

# Database Settings
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=kjarvis
DB_PORT=5432

# Redis Settings
REDIS_PORT=6379

# K-Auth Configuration (Identity Provider)
# These credentials are auto-injected into K-Auth on startup
ADMIN_EMAIL=admin@k-jarvis.com
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}
JWT_SECRET_KEY=${JWT_SECRET}

# K-Jarvis Orchestrator OAuth Client
# Used by K-Jarvis Backend to authenticate with K-Auth
KJARVIS_CLIENT_ID=${KJARVIS_CLIENT_ID}
KJARVIS_CLIENT_SECRET=${KJARVIS_CLIENT_SECRET}

# K-Arc (MCPHub) OAuth Client
# Used by K-Arc Backend to authenticate with K-Auth
KARC_CLIENT_ID=${KARC_CLIENT_ID}
KARC_CLIENT_SECRET=${KARC_CLIENT_SECRET}

# LLM Configuration (Set your keys here)
LLM_PROVIDER=openai
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
AZURE_OPENAI_API_KEY=
AZURE_OPENAI_ENDPOINT=

# Logging
LOG_LEVEL=INFO
EOL

echo "✅ Configuration complete!"
echo ""
echo "🔐 Generated Credentials:"
echo "   Admin User:     admin"
echo "   Admin Password: ${ADMIN_PASSWORD}"
echo "   K-Jarvis Client ID: ${KJARVIS_CLIENT_ID}"
echo "   K-Arc Client ID:    ${KARC_CLIENT_ID}"
echo ""
echo "🚀 Next Steps:"
echo "   1. Open .env and add your LLM API Keys (OPENAI_API_KEY, etc.)"
echo "   2. Run: docker-compose -f docker-compose.opensource.yml up -d --build"
echo "   3. Login at http://localhost:4000 with admin / ${ADMIN_PASSWORD}"
echo ""
